# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 755bd7928ca1582a7283bec1ea0e7ffe6dbd80186062c29c8cdd4da5f2484fceada3ae5c095e86218716a42c7bd9c1c8ebbb6a60b3895ee16f8f6b2874e9299b

test:
  secret_key_base: 9f73251315b1e64cff08b1ca9acbe61163ca91605aa638269c095153fb2ad0fc81bc1a6f06abdf6d4209179d734d596f9acf69b2bdc13c213abfe4652c7098e4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
